version: '3'

services:
    zookeeper:
        image: wurstmeister/zookeeper:latest
        container_name: "zookeeper"
        restart: always
        ports:
            - "2181:2181"
    
    kafka:
        image: wurstmeister/kafka:2.12-2.2.0
        container_name: "kafka"
        ports:
            - "9092:9092"
        environment:
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
            KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
            KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
            KAFKA_BROKER_ID: 1
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        volumes:
            - /opt/app/kafka/data:/kafka
            - /var/run/docker.sock:/var/run/docker.sock
        depends_on:
            - zookeeper
            
    elasticsearch:
        image: elastic/elasticsearch:6.8.0
        container_name: "elasticsearch"
        environment:
#            - cluster.name=docker-cluster
            - bootstrap.memory_lock=true
            - xpack.security.enabled=false
            - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes:
            - /opt/app/elasticsearch/data:/usr/share/elasticsearch/data
        ports:
            - "9200:9200"
            
    elasticsearch-head:
        image: mobz/elasticsearch-head:5
        container_name: elasticsearch-head
        ports:
            - "9100:9100"
        links:
            - elasticsearch
    
    mbp-registry:
        build: ./mbp-registry
        image: mbp-registry:1.0.0
        container_name: mbp-registry
        ports:
            - "8761:8761"
    
    mbp-zipkin:
        build: ./mbp-zipkin
        image: mbp-zipkin:1.0.0
        container_name: mbp-zipkin
        ports:
            - "8411:8411"
        links:
            - zookeeper
            - kafka
            - elasticsearch